FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]



FROM tomcat:9-jdk11
COPY target/*.war /usr/local/tomcat.webapps/
